### ISSUE TITLE
Error with eclipse m2e-apt

### ISSUE THREAD

**Issue by DeepSnowNeeL** [jbosstools/m2e-apt#56]
No problem when I build from maven, but when eclipse auto-builds when using m2e-apt with "Experimental : Delegate annotation processing to maven plugins" 

I don't get my annotation processor executed (or maybe it crashes ?), I would love to know a way to get the full stacktrace but can't find anything in workspace/.metadata/log unless this error :

!ENTRY org.eclipse.m2e.logback.appender 4 0 2017-05-31 19:04:51.476
!MESSAGE error on execute: error during compilation

Which is present in eclipse Error Log view :

> null
> org.eclipse.m2e.logback.appender
> Error
> Wed May 31 20:10:24 CEST 2017
> error on execute: error during compilation
> 

But when I hover the error tooltip in my pom `<execution>` block I get this non-complete stack :

> Error executing (org.bsc.maven:maven-processor-plugin:2.0.5:process:process:generate-sources)
> 
> org.apache.maven.plugin.MojoExecutionException: Error executing
> 	at org.bsc.maven.plugin.processor.AbstractAnnotationProcessorMojo.execute(AbstractAnnotationProcessorMojo.java:204)
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
> 	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
> 	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
> 	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
> 	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
> 	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
> 	at org.jboss.tools.maven.apt.internal.processor.MavenProcessorBuildParticipant.build(MavenProcessorBuildParticipant.java:80)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
> 	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
> 	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
> 	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
> 	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
> 	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
> Caused by: java.lang.Exception: error during compilation
> 	at org.bsc.maven.plugin.processor.AbstractAnnotationProcessorMojo.executeWithExceptionsHandled(AbstractAnnotationProcessorMojo.java:353)
> 	at org.bsc.maven.plugin.processor.AbstractAnnotationProcessorMojo.execute(AbstractAnnotationProcessorMojo.java:197)
> 	... 33 more
> 

Relevent part of my pom :

```xml
			<plugin>
				<groupId>org.bsc.maven</groupId>
				<artifactId>maven-processor-plugin</artifactId>
				<version>2.0.5</version>
				<executions>
					<execution>
						<id>process</id>
						<goals>
							<goal>process</goal>
						</goals>
						<phase>generate-sources</phase>
					</execution>
					<execution>
						<id>process-test</id>
						<goals>
							<goal>process-test</goal>
						</goals>
						<phase>generate-test-sources</phase>
						<configuration>
							<sourceDirectory>./test</sourceDirectory>
						</configuration>
					</execution>
				</executions>

				<dependencies>
					<dependency>
						<groupId>rockpalm.it</groupId>
						<artifactId>ic2-annotation-processor</artifactId>
						<version>1.2.1-SNAPSHOT</version>
					</dependency>
				</dependencies>
			</plugin>
```

Thanks for helping

**Comment by DeepSnowNeeL** [comment]
Looks like updating maven-processor-plugin to 3.3.1 fixed the thing.. sorry !
